---

- name: Copy the keycloak service template file
  template:
    src: "keycloak-svc.yml.j2"
    dest: "{{ remote_path }}/keycloak-svc.yml"

- name: Copy the keycloak headless service template file
  template:
    src: "keycloak-headless-svc.yml.j2"
    dest: "{{ remote_path }}/keycloak-headless-svc.yml"

- name: Copy the keycloak config map template file
  template:
    src: "keycloak-cm.yml.j2"
    dest: "{{ remote_path }}/keycloak-cm.yml"

- name: Copy the keycloak tls secret template file
  template:
    src: "keycloak-tls.yml.j2"
    dest: "{{ remote_path }}/keycloak-tls.yml"

- name: Copy the keycloak ingress template file
  template:
    src: "keycloak-ing.yml.j2"
    dest: "{{ remote_path }}/keycloak-ing.yml"

- name: Copy the keycloak deployment template file
  template:
    src: "keycloak-dp.yml.j2"
    dest: "{{ remote_path }}/keycloak-dp.yml"

- name: Deploy keycloak service
  shell: kubectl --kubeconfig={{ kubeconfig }} replace --force -f {{ remote_path }}/keycloak-svc.yml
  run_once: true

- name: Deploy keycloak headless service
  shell: kubectl --kubeconfig={{ kubeconfig }} replace --force -f {{ remote_path }}/keycloak-headless-svc.yml
  run_once: true

- name: Deploy keycloak tls secret
  shell: kubectl --kubeconfig={{ kubeconfig }} replace --force -f {{ remote_path }}/keycloak-tls.yml
  run_once: true

- name: Deploy keycloak config map
  shell: kubectl --kubeconfig={{ kubeconfig }} replace --force -f {{ remote_path }}/keycloak-cm.yml
  run_once: true

- name: Deploy keycloak ingress
  shell: kubectl --kubeconfig={{ kubeconfig }} replace --force -f {{ remote_path }}/keycloak-ing.yml
  run_once: true

- name: Deploy keycloak deployment
  shell: kubectl --kubeconfig={{ kubeconfig }} replace --force -f {{ remote_path }}/keycloak-dp.yml
  run_once: true
