---

- name: Install various required packages
  hosts: all
  become: yes
  roles:
    - bootstrap
  tags: bootstrap,deploy

- name: Install and run etcd
  hosts: etcd
  become: yes
  roles:
    - etcd
  tags: etcd,deploy

- name: Install and run flannel
  hosts: all
  become: yes
  roles:
    - flannel
  tags: deploy, flannel

- name: Install and start Docker
  hosts: all
  become: yes
  roles:
    - docker
  tags: docker, deploy

- name: Install and start Kubernetes
  hosts: all
  become: yes
  roles:
    - kubernetes
  tags: kubernetes

- name: Start the Ingress controller
  hosts: kube-slave
  become: yes
  roles:
    - ingress-controller
  tags: ingress
