---

- name: Build image locally
  include_tasks: build.yml
  tags: build
  delegate_to: 127.0.0.1
  run_once: true

- name: Expand mmapfs usage
  sysctl:
    name: 'vm.max_map_count'
    value: '262144'
  tags: always

- name: Push to remote
  include_tasks: push.yml
  tags: push

- name: Deploy kibana to cluster
  include_tasks: deploy.yml
  tags: deploy
  
- name: Cleanup local pull dirs
  include_tasks: cleanup_pull.yml
  run_once: true
  tags: cleanup_pull, cleanup
  delegate_to: 127.0.0.1

- name: Cleanup push dirs
  include_tasks: cleanup_push.yml
  tags: cleanup_push, cleanup
