archive_name: kibana

git_repo: git@github.com:cloudtrust/elasticsearch-service.git

dockerfile: cloudtrust-kibana.dockerfile

pull_path: '{{ playbook_dir }}/pull/kibana'

dockerfile_path: '{{ pull_path }}/dockerfiles'
context: '{{ pull_path }}/build_context'
image_name: 'cloudtrust-kibana:{{ config_repo_name }}-{{ config_git_tag }}'

remote_path: /cloudtrust/elasticsearch

tls_secret_name: kibana-tls
tls_crt: tls.crt
tls_key: tls.key
server_name: ct-int-kibana.dev.elca.ch
