---
- name: Master Certificates
  include_tasks: master-certificates.yml
  when: inventory_hostname in groups['kube-master']
  tags: certificates, deploy


- name: Certificates
  include_tasks: certificates.yml
  tags: certificates, deploy
