---

- name: Copy CA certificate over
  copy:
    src: "certs/{{ item }}"
    dest: /etc/pki/ca-trust/source/anchors
    mode: 0440
    owner: root
    group: root
  with_items:
    - "{{ kube_ca_cert_file }}"

- name: Update CA trust
  command: update-ca-trust

- name: Create directory for kube certs
  file:
    path: "{{ kube_certs_dir }}"
    state: directory
    mode: 0770
    owner: root
    group: root

- name: Copy client CA certificate file
  copy:
    src: "certs/{{ item }}"
    dest: "{{ kube_certs_dir }}"
    mode: 0440
    owner: root
    group: root
  with_items:
    - "{{ kube_client_ca_cert_file }}"

