---
- name: Install docker-storage file
  copy:
    src: '{{ pull_path }}/deploy/common/etc/sysconfig/docker-storage-setup'
    dest: '/etc/sysconfig/docker-storage-setup'
    mode: 0755

- name: Set the container SELinux boolean
  seboolean:
    name: container_manage_cgroup
    persistent: yes
    state: yes

- name: Run docker-storage-setup
  command: docker-storage-setup

- name: Enable and start docker
  systemd:
    name: docker
    daemon_reload: yes
    enabled: yes
    state: restarted