---

- name: Install Flannel
  shell: dnf install -y flannel

- name: Set Flannel config file directory
  set_fact:
    flannel_config_dir: "/etc/sysconfig"

- name: Create config file directory
  file: path={{ flannel_config_dir }} state=directory

- name: Install Flannel config file
  template: src=flanneld.j2 dest={{ flannel_config_dir }}/flanneld

- name: Install Flannel service file
  template:
    src: flanneld.service.j2
    dest: /etc/systemd/system/flanneld.service
