---

- name: Gather facts
  debug: msg='gather_facts for etcd'
  when: inventory_hostname in groups['etcd']

- name: Set facts about etcdctl command
  set_fact:
    peers: "{{ etcd_servers }}"
    conf_file: "/tmp/flannel-conf.json"
    conf_loc: "/{{ cluster_name }}/network/config"
    ca_file: "{{ etcd_certs_dir }}/{{ etcd_ca_file }}"
    cert_file: "{{ etcd_certs_dir }}/{{ etcd_client_cert_file }}"
    key_file: "{{ etcd_certs_dir }}/{{ etcd_client_key_file }}"
  run_once: true
  delegate_to: "{{ groups['etcd'][0] }}"

- name: Create flannel config file to go in etcd
  template: src=flannel-conf.json.j2 dest={{ conf_file }}
  run_once: true
  delegate_to: "{{ groups['etcd'][0] }}"

- name: Load the flannel config file into etcd
  shell: "/usr/bin/etcdctl --ca-file={{ ca_file }} --cert-file={{ cert_file }} --key-file={{ key_file }} --no-sync --peers={{ peers }} set {{ conf_loc }} < {{ conf_file }}"
  run_once: true
  delegate_to: "{{ groups['etcd'][0] }}"

- name: Clean up the flannel config file
  file: path=/tmp/flannel-config.json state=absent
  run_once: true
  delegate_to: "{{ groups['etcd'][0] }}"
