---

- name: Gather facts
  debug: msg='gather_facts for etcd'
  when: inventory_hostname in groups['etcd']

- name: Set facts about etcdctl command
  set_fact:
    conf_file: "/tmp/flannel-conf.json"
    conf_loc: "/{{ cluster_name }}/network/config"
  run_once: true
  delegate_to: "{{ groups['etcd'][0] }}"

- name: Create flannel config file to go in etcd
  template: src=flannel-conf.json.j2 dest={{ conf_file }}
  run_once: true
  delegate_to: "{{ groups['etcd'][0] }}"

- name: Load the flannel config file into etcd
  shell: "/usr/bin/etcdctl --ca-file={{ ca_cert }} --cert-file={{ etcd_client_cert }} --key-file={{ etcd_client_key }} --no-sync --peers={{ etcd_servers }} set {{ conf_loc }} < {{ conf_file }}"
  run_once: true
  delegate_to: "{{ groups['etcd'][0] }}"

- name: Clean up the flannel config file
  file: path=/tmp/flannel-config.json state=absent
  run_once: true
  delegate_to: "{{ groups['etcd'][0] }}"
