---

- name: Create remote directory
  file:
    path: "{{ remote_path }}"
    state: directory

- name: Deploy the client test image
  copy:
    src: '{{ pull_path }}/{{ archive_name }}.tar'
    dest: '{{ remote_path }}/{{ archive_name }}.tar'
    
- name: Import docker tar image
  docker_image:
    name: '{{ image_name }}'
    load_path: '{{ remote_path }}/{{ archive_name }}.tar'
    timeout: 300
    state: present
    force: yes
