---

- name: Make sure that the pull directory exists
  file:
    path: '{{ pull_path }}'
    state: directory

- name: Pull repository
  git:
    repo: '{{ git_repo }}'
    dest: '{{ pull_path }}'
    version: '{{ git_tag }}'

- name: Create build context
  file:
    path: '{{ context }}'
    state: directory

- name: Copy dockerfile to build context
  copy:
    src: '{{ osd_dockerfile }}'
    dest: '{{ context }}/Dockerfile'

- name: Build the image
  docker_image:
    name: '{{ osd_image_name }}'
    path: '{{ context }}'
    pull: False
    force: yes
    nocache: "{{ force | default('no') }}"
    state: present
    archive_path: '{{ pull_path }}/{{ osd_archive_name }}.tar'
    buildargs:
      ceph_service_git_tag: '{{ git_tag }}'
      ceph_tools_git_tag: '{{ ceph_tools_git_tag }}'
