---

- name: Build image locally
  import_tasks: build.yml
  tags: build
  run_once: true
  delegate_to: 127.0.0.1

- name: Push image to remote
  import_tasks: push.yml
  tags: push

- name: Deploy to cluster
  import_tasks: deploy.yml
  tags: deploy

- name: Cleanup local pull dirs
  import_tasks: cleanup_pull.yml
  run_once: true
  tags: cleanup_pull, cleanup
  delegate_to: 127.0.0.1

- name: Cleanup push dirs
  import_tasks: cleanup_push.yml
  tags: cleanup_push, cleanup
