---
- name: Create remote directory
  file:
    path: "{{ remote_path }}"
    state: directory

- name: Deploy the elasticsearch image
  copy:
    src: '{{ pull_path }}/{{ archive_name }}.tar'
    dest: '{{ remote_path }}/{{ archive_name }}.tar'
    
- name: Import docker tar image
  docker_image:
    name: '{{ image_name }}'
    load_path: '{{ remote_path }}/{{ archive_name }}.tar'
    state: present
    force: yes

- name: Deploy data configmap
  template:
    src: elasticsearch-data-cm.yml.j2
    dest: "{{ remote_path }}/elasticsearch-data-cm.yml"

- name: Deploy data deployment
  template:
    src: elasticsearch-data-svc.yml.j2
    dest: "{{ remote_path }}/elasticsearch-data-svc.yml"

- name: Deploy data deployment
  template:
    src: elasticsearch-data-dp.yml.j2
    dest: "{{ remote_path }}/elasticsearch-data-dp.yml"

- name: Create configmap
  shell: kubectl replace --force -f {{ remote_path }}/elasticsearch-data-svc.yml
  run_once: true

- name: Create configmap
  shell: kubectl replace --force -f {{ remote_path }}/elasticsearch-data-cm.yml
  run_once: true

- name: Create deployment
  shell: kubectl replace --force -f {{ remote_path }}/elasticsearch-data-dp.yml
  run_once: true

