---

- name: Build image locally
  import_tasks: build.yml
  tags: build
  run_once: true
  delegate_to: 127.0.0.1

- name: Export tar image and send to remote
  import_tasks: push.yml
  tags: push

- name: Deploy on kubernetes
  import_tasks: deploy.yml
  tags: deploy

- name: Cleanup local pull dirs
  import_tasks: cleanup_pull.yml
  run_once: true
  tags: cleanup_dir, cleanup
  delegate_to: 127.0.0.1

- name: Cleanup remote push dirs
  import_tasks: cleanup_push.yml
  tags: cleanup_dir, cleanup
