---
- name: Make sure directories exist
  file:
    path: '{{ remote_path }}'
    state: directory
    directory_mode: yes

- name: Push image to remote
  copy:
    src: '{{ context }}/{{ archive_name }}.tar'
    dest: '{{ remote_path }}/{{ archive_name }}.tar'
    directory_mode: yes

- name: Import docker tar image
  docker_image:
    name: '{{ image_name }}'
    load_path: '{{ remote_path }}/{{ archive_name }}.tar'
    state: present
    force: yes
